<a href="https://colab.research.google.com/github/alirezasaharkhiz9/python-for-DataAnalysis/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data analysis with Pandas

----

## Introduction to Pandas

**Pandas** is one of the most powerful and widely used open-source libraries for data manipulation and analysis in Python. It provides high-level data structures and methods designed to work seamlessly with structured data, such as tables (dataframes) and time-series data. **Pandas** is built on top of **NumPy**, and its main strength lies in handling large datasets, cleaning, transforming, and analyzing data efficiently.

In this introduction, we will explore the core concepts of **Pandas**, its main data structures, and why it is a go-to tool for data analysis.

----------
### Why Use Pandas?

There are several key reasons why **Pandas** is so popular in data science, machine learning, and other data-related fields:

1. **Easy Handling of Structured Data**:
   - **Pandas** provides two primary data structures: **Series** (for 1-dimensional data) and **DataFrame** (for 2-dimensional data). These structures are optimized for performance and allow for easy access, filtering, and manipulation of data.

2. **Data Cleaning and Transformation**:
   - **Pandas** excels at data preprocessing tasks such as handling missing values, removing duplicates, merging datasets, and reshaping data. It allows you to quickly clean and organize data for further analysis.

3. **Powerful Data Analysis**:
   - With built-in functions like groupby, pivoting, and aggregation, **Pandas** offers comprehensive support for performing complex data analysis. It can quickly summarize and analyze large datasets.

4. **Support for Multiple Data Formats**:
   - **Pandas** supports reading and writing various data formats including **CSV**, **Excel**, **SQL**, and **JSON**, making it easy to work with data from different sources.

5. **Integration with Other Libraries**:
   - **Pandas** integrates well with other data analysis and visualization libraries such as **Matplotlib**, **Seaborn**, and **SciPy**. Itâ€™s often used as the first step in data preprocessing before further analysis or visualization.


---------------

### Key Data Structures in Pandas

The core of **Pandas** is its two main data structures:

1. **Series**:
   - A **Series** is a one-dimensional array-like object that can hold any data type (integers, floats, strings, Python objects, etc.). It has an index attached to it, which makes it easy to access individual elements.
   - Think of a **Series** as a single column in a table.

2. **DataFrame**:
   - A **DataFrame** is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). It is the most widely used object in **Pandas** and is often compared to a table or spreadsheet in Excel.
   - A **DataFrame** can hold a variety of data types (e.g., integers, floats, strings, and even other **Series**). You can think of it as a collection of **Series**, where each **Series** represents a column in the **DataFrame**.

------------

### Why Pandas is Essential for Data Analysis

**Pandas** provides intuitive and flexible tools for working with structured data, and it is an essential part of the data science ecosystem. Whether you're working with a small dataset or a large, complex one, **Pandas** can help you:

- **Clean and preprocess data**: Handling missing data, duplicates, and transforming data into the right format.
- **Summarize data**: Using aggregation, filtering, and grouping to extract meaningful insights from your dataset.
- **Merging and joining data**: Combining datasets from different sources in an efficient manner.
- **Visualization**: Plotting and visualizing data directly from **Pandas** (often in combination with libraries like **Matplotlib** and **Seaborn**).

![1725880873576.jpg]()

Series

![create-series-in-python-pandas-0.png]()

Data Frame

![creating_dataframe1.png]()

## Import pandas

In [ ]:
#!pip install pandas

In [1]:
# pandas
import pandas as pd

# numpy
import numpy as np

## Create Series

In [ ]:
my_seri = pd.Series([1, 2, 4, 8])
print(my_seri)

0    1
1    2
2    4
3    8
dtype: int64

In [ ]:
my_seri = pd.Series([1, 2, 4, 8], index=['a', 'b', 'c', 'd'])
print(my_seri)

a    1
b    2
c    4
d    8
dtype: int64

In [ ]:
arr = np.array([1, 2, 4, 8])
my_seri = pd.Series(arr)
print(my_seri)

0    1
1    2
2    4
3    8
dtype: int64

In [ ]:
my_seri

0    1
1    2
2    4
3    8
dtype: int64

In [ ]:
my_dict = dict(
    a=10,
    b=30,
    c=50
)
# {}

In [ ]:
my_seri = pd.Series(my_dict)
my_seri

a    10
b    30
c    50
dtype: int64

## Attributes and Mathod Series

----------

#### Attributes:
dtype, size, ndim, values, index

---------

#### Mathod:
head(), tail(), sort_index(), sort_values()

In [ ]:
my_seri.dtype

dtype('int64')

In [ ]:
my_seri.size

3

In [ ]:
my_seri.ndim

1

In [ ]:
my_seri.values

array([10, 30, 50])

In [ ]:
my_seri.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
arr = np.random.randn(10,)
arr.ndim

1

In [ ]:
arr

array([-0.1558967 ,  0.45528975, -0.04881561,  0.8291705 ,  1.70715014,
       -0.77385755, -2.4180687 ,  1.06434731, -0.21348848,  0.31506533])

In [ ]:
seri = pd.Series(arr)
seri

0   -0.155897
1    0.455290
2   -0.048816
3    0.829170
4    1.707150
5   -0.773858
6   -2.418069
7    1.064347
8   -0.213488
9    0.315065
dtype: float64

In [ ]:
seri.head()

0   -0.155897
1    0.455290
2   -0.048816
3    0.829170
4    1.707150
dtype: float64

In [ ]:
seri.head(3)

0   -0.155897
1    0.455290
2   -0.048816
dtype: float64

In [ ]:
seri.tail()

5   -0.773858
6   -2.418069
7    1.064347
8   -0.213488
9    0.315065
dtype: float64

In [ ]:
seri.sort_values()

6   -2.418069
5   -0.773858
8   -0.213488
0   -0.155897
2   -0.048816
9    0.315065
1    0.455290
3    0.829170
7    1.064347
4    1.707150
dtype: float64

In [ ]:
seri.sort_index()

0   -0.155897
1    0.455290
2   -0.048816
3    0.829170
4    1.707150
5   -0.773858
6   -2.418069
7    1.064347
8   -0.213488
9    0.315065
dtype: float64

## Index, Slicing Series

In [ ]:
seri[2]

-0.04881561462946776

In [ ]:
seri[2:5]

2   -0.048816
3    0.829170
4    1.707150
dtype: float64

In [ ]:
seri[::2]

0   -0.155897
2   -0.048816
4    1.707150
6   -2.418069
8   -0.213488
dtype: float64

## Filter Series

In [ ]:
seri > 0.5

0    False
1    False
2    False
3     True
4     True
5    False
6    False
7     True
8    False
9    False
dtype: bool

In [ ]:
seri[seri > 0.5]

3    0.829170
4    1.707150
7    1.064347
dtype: float64

In [ ]:
con = seri < 0
con

0     True
1    False
2     True
3    False
4    False
5     True
6     True
7    False
8     True
9    False
dtype: bool

In [ ]:
seri[con]

0   -0.155897
2   -0.048816
5   -0.773858
6   -2.418069
8   -0.213488
dtype: float64

## Create Data Frame

In [ ]:
x1 = np.random.randint(1, 10, size=10)
x2 = np.random.randint(20, 40, size=10)
x1

array([4, 4, 7, 3, 4, 4, 6, 5, 6, 7])

In [ ]:
my_dict = dict(
    x1=x1,
    x2=x2
)

In [ ]:
data = pd.DataFrame(my_dict)
data

   x1  x2
0   4  31
1   4  39
2   7  25
3   3  35
4   4  29
5   4  30
6   6  32
7   5  29
8   6  29
9   7  31

In [ ]:
x = np.random.randint(10, 100, size=(10, 3))
x

array([[57, 43, 62],
       [52, 85, 57],
       [46, 33, 72],
       [85, 13, 29],
       [58, 56, 84],
       [47, 70, 23],
       [10, 40, 34],
       [62, 13, 64],
       [23, 25, 18],
       [92, 41, 13]])

In [ ]:
data = pd.DataFrame(x, columns=['x1', 'x2', 'x3'])
data

   x1  x2  x3
0  57  43  62
1  52  85  57
2  46  33  72
3  85  13  29
4  58  56  84
5  47  70  23
6  10  40  34
7  62  13  64
8  23  25  18
9  92  41  13

## Read File with Pandas

In [2]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DataSet/BostonHousing.csv')
data.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,NaN,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

## Attributes

-----------------

dtypes

size

ndim

columns

shape

index

values

In [ ]:
data.dtypes

crim       float64
zn         float64
indus      float64
chas         int64
nox        float64
rm         float64
age        float64
dis        float64
rad          int64
tax          int64
ptratio    float64
b          float64
lstat      float64
medv       float64
dtype: object

In [ ]:
data.size

7098

In [ ]:
data.shape

(507, 14)

In [ ]:
data.ndim

2

In [ ]:
data.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [ ]:
data.values

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01],
       [5.0590e-02, 0.0000e+00, 4.4900e+00, ..., 3.9690e+02, 9.6200e+00,
        2.3900e+01]])

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01],
       [5.0590e-02, 0.0000e+00, 4.4900e+00, ..., 3.9690e+02, 9.6200e+00,
        2.3900e+01]])

In [ ]:
data.values.shape

(507, 14)

In [ ]:
data.index

RangeIndex(start=0, stop=507, step=1)

## Methods

### head()

In [ ]:
data.head(20)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,NaN,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9
10,0.22489,12.5,7.87,0,0.524,6.377,94.3,6.3467,5,311,15.2,392.52,20.45,15.0
11,0.11747,12.5,7.87,0,0.524,6.009,82.9,6.2267,5,311,15.2,396.90,13.27,18.9
12,0.09378,12.5,7.87,0,0.524,5.889,39.0,5.4509,5,311,15.2,390.50,15.71,21.7
13,0.62976,0.0,8.14,0,0.538,5.949,61.8,4.7075,4,307,21.0,396.90,8.26,20.4
14,0.63796,0.0,8.14,0,0.538,6.096,84.5,4.4619,4,307,21.0,380.02,10.26,18.2
15,0.62739,0.0,8.14,0,0.538,5.834,56.5,4.4986,4,307,21.0,395.62,8.47,19.9
16,1.05393,0.0,8.14,0,0.538,5.935,29.3,4.4986,4,307,21.0,386.85,6.58,23.1
17,0.78420,0.0,8.14,0,0.538,5.990,81.7,4.2579,4,307,21.0,386.75,14.67,17.5
18,0.80271,0.0,8.14,0,0.538,5.456,36.6,3.7965,4,307,21.0,288.99,11.69,20.2
19,0.72580,0.0,8.14,0,0.538,5.727,69.5,3.7965,4,307,21.0,390.95,11.28,18.2

### tail()

In [ ]:
data.tail(10)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
497,0.26838,0.0,9.69,0,0.585,5.794,70.6,2.8927,6,391,19.2,396.90,14.10,18.3
498,0.23912,0.0,9.69,0,0.585,6.019,65.3,2.4091,6,391,19.2,396.90,12.92,21.2
499,0.17783,0.0,9.69,0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33,16.8
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9
506,0.05059,0.0,4.49,0,0.449,6.389,48.0,4.7794,3,247,18.5,396.90,9.62,23.9

In [ ]:
data

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,NaN,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9
506,0.05059,0.0,4.49,0,0.449,6.389,48.0,4.7794,3,247,18.5,396.90,9.62,23.9

### info()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     507 non-null    float64
 1   zn       507 non-null    float64
 2   indus    507 non-null    float64
 3   chas     507 non-null    int64
 4   nox      507 non-null    float64
 5   rm       507 non-null    float64
 6   age      505 non-null    float64
 7   dis      507 non-null    float64
 8   rad      507 non-null    int64
 9   tax      507 non-null    int64
 10  ptratio  507 non-null    float64
 11  b        507 non-null    float64
 12  lstat    507 non-null    float64
 13  medv     507 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.6 KB

### describe()

In [ ]:
data.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,507.000000,507.000000,507.000000,507.000000,507.000000,507.000000,505.000000,507.000000,507.000000,507.000000,507.000000,507.000000,507.000000,507.000000
mean,3.606496,11.341223,11.123669,0.069034,0.554487,6.284840,68.531485,3.796984,9.536489,407.919132,18.455621,356.753373,12.647081,22.535503
std,8.594498,23.304861,6.859925,0.253762,0.115858,0.701938,28.152879,2.104083,8.703513,168.522700,2.162806,91.222103,7.135273,9.188212
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.081930,0.000000,5.160000,0.000000,0.449000,5.886000,45.000000,2.100350,4.000000,279.000000,17.400000,375.425000,6.970000,17.050000
50%,0.253870,0.000000,9.690000,0.000000,0.538000,6.209000,77.300000,3.215700,5.000000,330.000000,19.000000,391.450000,11.340000,21.200000
75%,3.675945,12.500000,18.100000,0.000000,0.624000,6.622000,94.100000,5.164950,24.000000,666.000000,20.200000,396.235000,16.950000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

### sort_values()

In [ ]:
data.sort_values('crim')

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
284,0.00906,90.0,2.97,0,0.400,7.088,20.8,7.3073,1,285,15.3,394.72,7.85,32.2
285,0.01096,55.0,2.25,0,0.389,6.453,31.9,7.3073,1,300,15.3,394.72,8.23,22.0
341,0.01301,35.0,1.52,0,0.442,7.241,49.3,7.0379,1,284,15.5,394.74,5.49,32.7
55,0.01311,90.0,1.22,0,0.403,7.249,21.9,8.6966,5,226,17.9,395.93,4.81,35.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,45.74610,0.0,18.10,0,0.693,4.519,100.0,1.6582,24,666,20.2,88.27,36.98,7.0
410,51.13580,0.0,18.10,0,0.597,5.757,100.0,1.4130,24,666,20.2,2.60,10.11,15.0
405,67.92080,0.0,18.10,0,0.693,5.683,100.0,1.4254,24,666,20.2,384.97,22.98,5.0
418,73.53410,0.0,18.10,0,0.679,5.957,100.0,1.8026,24,666,20.2,16.45,20.62,8.8
380,88.97620,0.0,18.10,0,0.671,6.968,91.9,1.4165,24,666,20.2,396.90,17.21,10.4

## Selection

### data['column names']

In [3]:
data['age']

0      65.2
1      78.9
2      61.1
3       NaN
4      54.2
       ...
502    76.7
503    91.0
504    89.3
505    80.8
506    48.0
Name: age, Length: 507, dtype: float64

In [8]:
data[20:30]

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
20,1.25179,0.0,8.14,0,0.538,5.570,98.1,3.7979,4,307,21.0,376.57,21.02,13.6
21,0.85204,0.0,8.14,0,0.538,5.965,89.2,4.0123,4,307,21.0,392.53,13.83,19.6
22,1.23247,0.0,8.14,0,0.538,6.142,91.7,3.9769,4,307,21.0,396.90,18.72,15.2
23,0.98843,0.0,8.14,0,0.538,5.813,100.0,4.0952,4,307,21.0,394.54,19.88,14.5
24,0.75026,0.0,8.14,0,0.538,5.924,94.1,4.3996,4,307,21.0,394.33,16.30,15.6
25,0.84054,0.0,8.14,0,0.538,5.599,85.7,4.4546,4,307,21.0,303.42,16.51,13.9
26,0.67191,0.0,8.14,0,0.538,5.813,90.3,4.6820,4,307,21.0,376.88,14.81,16.6
27,0.95577,0.0,8.14,0,0.538,6.047,88.8,4.4534,4,307,21.0,306.38,17.28,14.8
28,0.77299,0.0,8.14,0,0.538,6.495,94.4,4.4547,4,307,21.0,387.94,12.80,18.4
29,1.00245,0.0,8.14,0,0.538,6.674,87.3,4.2390,4,307,21.0,380.23,11.98,21.0

### data.iloc[]
#### [row: start:end:step, col: start:end:step]

In [9]:
data.iloc[20:31, 0:3]

       crim   zn  indus
20  1.25179  0.0   8.14
21  0.85204  0.0   8.14
22  1.23247  0.0   8.14
23  0.98843  0.0   8.14
24  0.75026  0.0   8.14
25  0.84054  0.0   8.14
26  0.67191  0.0   8.14
27  0.95577  0.0   8.14
28  0.77299  0.0   8.14
29  1.00245  0.0   8.14
30  1.13081  0.0   8.14

In [10]:
data.iloc[:, 0]
# data['crim']

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...
502    0.04527
503    0.06076
504    0.10959
505    0.04741
506    0.05059
Name: crim, Length: 507, dtype: float64

### data.loc[]

In [13]:
data.loc[40:51, 'age':'b']

     age     dis  rad  tax  ptratio       b
40  15.8  5.4011    3  252     18.3  395.62
41   2.9  5.7209    3  233     17.9  385.41
42   6.6  5.7209    3  233     17.9  383.37
43   6.5  5.7209    3  233     17.9  394.46
44  40.0  5.7209    3  233     17.9  389.39
45  33.8  5.1004    3  233     17.9  396.90
46  33.3  5.1004    3  233     17.9  396.90
47  85.5  5.6894    3  233     17.9  392.74
48  95.3  5.8700    3  233     17.9  396.90
49  62.0  6.0877    3  233     17.9  396.90
50  45.7  6.8147    4  243     16.8  395.56
51  63.0  6.8147    4  243     16.8  393.97

In [16]:
data.loc[40:51:3, 'age':'b':2]

     age  rad  ptratio
40  15.8    3     18.3
43   6.5    3     17.9
46  33.3    3     17.9
49  62.0    3     17.9

In [17]:
data.loc[:, 'crim':'age']

        crim    zn  indus  chas    nox     rm   age
0    0.00632  18.0   2.31     0  0.538  6.575  65.2
1    0.02731   0.0   7.07     0  0.469  6.421  78.9
2    0.02729   0.0   7.07     0  0.469  7.185  61.1
3    0.03237   0.0   2.18     0  0.458  6.998   NaN
4    0.06905   0.0   2.18     0  0.458  7.147  54.2
..       ...   ...    ...   ...    ...    ...   ...
502  0.04527   0.0  11.93     0  0.573  6.120  76.7
503  0.06076   0.0  11.93     0  0.573  6.976  91.0
504  0.10959   0.0  11.93     0  0.573  6.794  89.3
505  0.04741   0.0  11.93     0  0.573  6.030  80.8
506  0.05059   0.0   4.49     0  0.449  6.389  48.0

[507 rows x 7 columns]

In [19]:
data.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [18]:
# remove age variable
data.loc[:, data.columns != 'age']

,crim,zn,indus,chas,nox,rm,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.04527,0.0,11.93,0,0.573,6.120,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,2.5050,1,273,21.0,396.90,7.88,11.9
506,0.05059,0.0,4.49,0,0.449,6.389,4.7794,3,247,18.5,396.90,9.62,23.9

In [24]:
# data.loc for filter
data.loc[data['age'] > 99, 'crim':'age']

         crim    zn  indus  chas    nox     rm    age
8     0.21124  12.5   7.87     0  0.524  5.631  100.0
23    0.98843   0.0   8.14     0  0.538  5.813  100.0
31    1.35472   0.0   8.14     0  0.538  6.072  100.0
141   1.62864   0.0  21.89     0  0.624  5.019  100.0
142   3.32105   0.0  19.58     1  0.871  5.403  100.0
143   4.09740   0.0  19.58     0  0.871  5.468  100.0
145   2.37934   0.0  19.58     0  0.871  6.130  100.0
146   2.15505   0.0  19.58     0  0.871  5.628  100.0
151   1.49632   0.0  19.58     0  0.871  5.404  100.0
158   1.34284   0.0  19.58     0  0.605  6.066  100.0
159   1.42502   0.0  19.58     0  0.871  6.510  100.0
209   0.43571   0.0  10.59     1  0.489  5.344  100.0
258   0.66351  20.0   3.97     0  0.647  7.333  100.0
259   0.65665  20.0   3.97     0  0.647  6.842  100.0
367  13.52220   0.0  18.10     0  0.631  3.863  100.0
368   4.89822   0.0  18.10     0  0.631  4.970  100.0
371   9.23230   0.0  18.10     0  0.631  6.216  100.0
373  11.10810   0.0  18.10     0  0.668  4.906  100.0
374  18.49820   0.0  18.10     0  0.668  4.138  100.0
379  17.86670   0.0  18.10     0  0.671  6.223  100.0
381  15.87440   0.0  18.10     0  0.671  6.545   99.1
382   9.18702   0.0  18.10     0  0.700  5.536  100.0
383   7.99248   0.0  18.10     0  0.700  5.520  100.0
386  24.39380   0.0  18.10     0  0.700  4.652  100.0
388  14.33370   0.0  18.10     0  0.700  4.880  100.0
398  38.35180   0.0  18.10     0  0.693  5.453  100.0
400  25.04610   0.0  18.10     0  0.693  5.987  100.0
401  14.23620   0.0  18.10     0  0.693  6.343  100.0
402   9.59571   0.0  18.10     0  0.693  6.404  100.0
405  67.92080   0.0  18.10     0  0.693  5.683  100.0
406  20.71620   0.0  18.10     0  0.659  4.138  100.0
407  11.95110   0.0  18.10     0  0.659  5.608  100.0
409  14.43830   0.0  18.10     0  0.597  6.852  100.0
410  51.13580   0.0  18.10     0  0.597  5.757  100.0
411  14.05070   0.0  18.10     0  0.597  6.657  100.0
412  18.81100   0.0  18.10     0  0.597  4.628  100.0
413  28.65580   0.0  18.10     0  0.597  5.155  100.0
414  45.74610   0.0  18.10     0  0.693  4.519  100.0
415  18.08460   0.0  18.10     0  0.679  6.434  100.0
418  73.53410   0.0  18.10     0  0.679  5.957  100.0
420  11.08740   0.0  18.10     0  0.718  6.411  100.0
437  15.17720   0.0  18.10     0  0.740  6.152  100.0
442   5.66637   0.0  18.10     0  0.740  6.219  100.0
443   9.96654   0.0  18.10     0  0.740  6.485  100.0
453   8.24809   0.0  18.10     0  0.713  7.393   99.3

In [25]:
data.loc[data['age'] > 99, 'crim']

8       0.21124
23      0.98843
31      1.35472
141     1.62864
142     3.32105
143     4.09740
145     2.37934
146     2.15505
151     1.49632
158     1.34284
159     1.42502
209     0.43571
258     0.66351
259     0.65665
367    13.52220
368     4.89822
371     9.23230
373    11.10810
374    18.49820
379    17.86670
381    15.87440
382     9.18702
383     7.99248
386    24.39380
388    14.33370
398    38.35180
400    25.04610
401    14.23620
402     9.59571
405    67.92080
406    20.71620
407    11.95110
409    14.43830
410    51.13580
411    14.05070
412    18.81100
413    28.65580
414    45.74610
415    18.08460
418    73.53410
420    11.08740
437    15.17720
442     5.66637
443     9.96654
453     8.24809
Name: crim, dtype: float64

In [26]:
data.loc[data['age'] > 99, ['crim', 'age']]

         crim    age
8     0.21124  100.0
23    0.98843  100.0
31    1.35472  100.0
141   1.62864  100.0
142   3.32105  100.0
143   4.09740  100.0
145   2.37934  100.0
146   2.15505  100.0
151   1.49632  100.0
158   1.34284  100.0
159   1.42502  100.0
209   0.43571  100.0
258   0.66351  100.0
259   0.65665  100.0
367  13.52220  100.0
368   4.89822  100.0
371   9.23230  100.0
373  11.10810  100.0
374  18.49820  100.0
379  17.86670  100.0
381  15.87440   99.1
382   9.18702  100.0
383   7.99248  100.0
386  24.39380  100.0
388  14.33370  100.0
398  38.35180  100.0
400  25.04610  100.0
401  14.23620  100.0
402   9.59571  100.0
405  67.92080  100.0
406  20.71620  100.0
407  11.95110  100.0
409  14.43830  100.0
410  51.13580  100.0
411  14.05070  100.0
412  18.81100  100.0
413  28.65580  100.0
414  45.74610  100.0
415  18.08460  100.0
418  73.53410  100.0
420  11.08740  100.0
437  15.17720  100.0
442   5.66637  100.0
443   9.96654  100.0
453   8.24809   99.3

## Conditional Selection (filter)

In [27]:
data['age'] > 99

0      False
1      False
2      False
3      False
4      False
       ...
502    False
503    False
504    False
505    False
506    False
Name: age, Length: 507, dtype: bool

In [28]:
data[data['age'] > 99]

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
23,0.98843,0.0,8.14,0,0.538,5.813,100.0,4.0952,4,307,21.0,394.54,19.88,14.5
31,1.35472,0.0,8.14,0,0.538,6.072,100.0,4.1750,4,307,21.0,376.73,13.04,14.5
141,1.62864,0.0,21.89,0,0.624,5.019,100.0,1.4394,4,437,21.2,396.90,34.41,14.4
142,3.32105,0.0,19.58,1,0.871,5.403,100.0,1.3216,5,403,14.7,396.90,26.82,13.4
143,4.09740,0.0,19.58,0,0.871,5.468,100.0,1.4118,5,403,14.7,396.90,26.42,15.6
145,2.37934,0.0,19.58,0,0.871,6.130,100.0,1.4191,5,403,14.7,172.91,27.80,13.8
146,2.15505,0.0,19.58,0,0.871,5.628,100.0,1.5166,5,403,14.7,169.27,16.65,15.6
151,1.49632,0.0,19.58,0,0.871,5.404,100.0,1.5916,5,403,14.7,341.60,13.28,19.6
158,1.34284,0.0,19.58,0,0.605,6.066,100.0,1.7573,5,403,14.7,353.89,6.43,24.3
159,1.42502,0.0,19.58,0,0.871,6.510,100.0,1.7659,5,403,14.7,364.31,7.39,23.3
209,0.43571,0.0,10.59,1,0.489,5.344,100.0,3.8750,4,277,18.6,396.90,23.09,20.0
258,0.66351,20.0,3.97,0,0.647,7.333,100.0,1.8946,5,264,13.0,383.29,7.79,36.0
259,0.65665,20.0,3.97,0,0.647,6.842,100.0,2.0107,5,264,13.0,391.93,6.90,30.1
367,13.52220,0.0,18.10,0,0.631,3.863,100.0,1.5106,24,666,20.2,131.42,13.33,23.1
368,4.89822,0.0,18.10,0,0.631,4.970,100.0,1.3325,24,666,20.2,375.52,3.26,50.0
371,9.23230,0.0,18.10,0,0.631,6.216,100.0,1.1691,24,666,20.2,366.15,9.53,50.0
373,11.10810,0.0,18.10,0,0.668,4.906,100.0,1.1742,24,666,20.2,396.90,34.77,13.8
374,18.49820,0.0,18.10,0,0.668,4.138,100.0,1.1370,24,666,20.2,396.90,37.97,13.8
379,17.86670,0.0,18.10,0,0.671,6.223,100.0,1.3861,24,666,20.2,393.74,21.78,10.2
381,15.87440,0.0,18.10,0,0.671,6.545,99.1,1.5192,24,666,20.2,396.90,21.08,10.9
382,9.18702,0.0,18.10,0,0.700,5.536,100.0,1.5804,24,666,20.2,396.90,23.60,11.3
383,7.99248,0.0,18.10,0,0.700,5.520,100.0,1.5331,24,666,20.2,396.90,24.56,12.3
386,24.39380,0.0,18.10,0,0.700,4.652,100.0,1.4672,24,666,20.2,396.90,28.28,10.5
388,14.33370,0.0,18.10,0,0.700,4.880,100.0,1.5895,24,666,20.2,372.92,30.62,10.2
398,38.35180,0.0,18.10,0,0.693,5.453,100.0,1.4896,24,666,20.2,396.90,30.59,5.0
400,25.04610,0.0,18.10,0,0.693,5.987,100.0,1.5888,24,666,20.2,396.90,26.77,5.6
401,14.23620,0.0,18.10,0,0.693,6.343,100.0,1.5741,24,666,20.2,396.90,20.32,7.2
402,9.59571,0.0,18.10,0,0.693,6.404,100.0,1.6390,24,666,20.2,376.11,20.31,12.1
405,67.92080,0.0,18.10,0,0.693,5.683,100.0,1.4254,24,666,20.2,384.97,22.98,5.0
406,20.71620,0.0,18.10,0,0.659,4.138,100.0,1.1781,24,666,20.2,370.22,23.34,11.9
407,11.95110,0.0,18.10,0,0.659,5.608,100.0,1.2852,24,666,20.2,332.09,12.13,27.9
409,14.43830,0.0,18.10,0,0.597,6.852,100.0,1.4655,24,666,20.2,179.36,19.78,27.5
410,51.13580,0.0,18.10,0,0.597,5.757,100.0,1.4130,24,666,20.2,2.60,10.11,15.0
411,14.05070,0.0,18.10,0,0.597,6.657,100.0,1.5275,24,666,20.2,35.05,21.22,17.2
412,18.81100,0.0,18.10,0,0.597,4.628,100.0,1.5539,24,666,20.2,28.79,34.37,17.9
413,28.65580,0.0,18.10,0,0.597,5.155,100.0,1.5894,24,666,20.2,210.97,20.08,16.3
414,45.74610,0.0,18.10,0,0.693,4.519,100.0,1.6582,24,666,20.2,88.27,36.98,7.0
415,18.08460,0.0,18.10,0,0.679,6.434,100.0,1.8347,24,666,20.2,27.25,29.05,7.2
418,73.53410,0.0,18.10,0,0.679,5.957,100.0,1.8026,24,666,20.2,16.45,20.62,8.8
420,11.08740,0.0,18.10,0,0.718,6.411,100.0,1.8589,24,666,20.2,318.75,15.02,16.7
437,15.17720,0.0,18.10,0,0.740,6.152,100.0,1.9142,24,666,20.2,9.32,26.45,8.7
442,5.66637,0.0,18.10,0,0.740,6.219,100.0,2.0048,24,666,20.2,395.69,16.59,18.4
443,9.96654,0.0,18.10,0,0.740,6.485,100.0,1.9784,24,666,20.2,386.73,18.85,15.4
453,8.24809,0.0,18.10,0,0.713,7.393,99.3,2.4527,24,666,20.2,375.87,16.74,17.8

In [30]:
data[data['age'] > 99].head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
23,0.98843,0.0,8.14,0,0.538,5.813,100.0,4.0952,4,307,21.0,394.54,19.88,14.5
31,1.35472,0.0,8.14,0,0.538,6.072,100.0,4.1750,4,307,21.0,376.73,13.04,14.5
141,1.62864,0.0,21.89,0,0.624,5.019,100.0,1.4394,4,437,21.2,396.90,34.41,14.4
142,3.32105,0.0,19.58,1,0.871,5.403,100.0,1.3216,5,403,14.7,396.90,26.82,13.4

In [32]:
data[data['age'] > 99]['crim']

8       0.21124
23      0.98843
31      1.35472
141     1.62864
142     3.32105
143     4.09740
145     2.37934
146     2.15505
151     1.49632
158     1.34284
159     1.42502
209     0.43571
258     0.66351
259     0.65665
367    13.52220
368     4.89822
371     9.23230
373    11.10810
374    18.49820
379    17.86670
381    15.87440
382     9.18702
383     7.99248
386    24.39380
388    14.33370
398    38.35180
400    25.04610
401    14.23620
402     9.59571
405    67.92080
406    20.71620
407    11.95110
409    14.43830
410    51.13580
411    14.05070
412    18.81100
413    28.65580
414    45.74610
415    18.08460
418    73.53410
420    11.08740
437    15.17720
442     5.66637
443     9.96654
453     8.24809
Name: crim, dtype: float64

In [34]:
data[data['crim'] > 50]

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
380,88.9762,0.0,18.1,0,0.671,6.968,91.9,1.4165,24,666,20.2,396.90,17.21,10.4
405,67.9208,0.0,18.1,0,0.693,5.683,100.0,1.4254,24,666,20.2,384.97,22.98,5.0
410,51.1358,0.0,18.1,0,0.597,5.757,100.0,1.4130,24,666,20.2,2.60,10.11,15.0
418,73.5341,0.0,18.1,0,0.679,5.957,100.0,1.8026,24,666,20.2,16.45,20.62,8.8

## Rename Columns

In [35]:
# rename col
data.rename(columns={'crim':'CRIM'})

,CRIM,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,NaN,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9
506,0.05059,0.0,4.49,0,0.449,6.389,48.0,4.7794,3,247,18.5,396.90,9.62,23.9

In [36]:
data

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,NaN,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9
506,0.05059,0.0,4.49,0,0.449,6.389,48.0,4.7794,3,247,18.5,396.90,9.62,23.9

In [37]:
data.rename(columns={'crim':'CRIM'}, inplace=True)

In [38]:
data

,CRIM,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,NaN,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9
506,0.05059,0.0,4.49,0,0.449,6.389,48.0,4.7794,3,247,18.5,396.90,9.62,23.9

## Adding and Removing Rows and Columns

### Adding Rows and Columns

In [39]:
# add col
data['LSTAT'] = data['lstat'] / 100

In [40]:
data.head()

,CRIM,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0,0.0498
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6,0.0914
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7,0.0403
3,0.03237,0.0,2.18,0,0.458,6.998,NaN,6.0622,3,222,18.7,394.63,2.94,33.4,0.0294
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2,0.0533

In [41]:
data.shape

(507, 15)

In [45]:
# add row
# data.loc[507] = [1.5, 0, ]

### Removing Rows and Columns

In [ ]:
# data = data.loc[:, 'age']

In [46]:
# remove col
data.drop(columns='LSTAT', inplace=True, axis=1)

In [47]:
data.head()

,CRIM,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,NaN,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [48]:
# remove row
# data.drop(index=506, inplace=True)

## NA values

### Check NA values

In [49]:
data.isnull()

,CRIM,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,False,False,False,False,False,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False,False,False,False,False,False
505,False,False,False,False,False,False,False,False,False,False,False,False,False,False
506,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [50]:
data.isnull().sum()

CRIM       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        2
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

### Dropping Null Values: Dropna()

In [51]:
# drop na
data.dropna(inplace=True)

In [52]:
data.isnull().sum()

CRIM       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

### Filling Null Values: Fillna()

In [53]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DataSet/BostonHousing.csv')

In [54]:
# fill na age variable
data['age'].fillna(data['age'].mean(), inplace=True)

<ipython-input-54-59bae4183ae1>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['age'].fillna(data['age'].mean(), inplace=True)

In [55]:
data.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

## Duplicate

### Check Duplicate

In [56]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
502    False
503    False
504    False
505    False
506     True
Length: 507, dtype: bool

In [57]:
data.duplicated().sum()

1

### Drop duplicate

In [58]:
data.drop_duplicates(inplace=True)

In [60]:
data.duplicated().sum()

0

In [61]:
data.shape

(506, 14)

## groupby, Aggregate

### aggregate

In [62]:
data['age'].mean()

68.57206120612061

In [63]:
data['crim'].mean()

3.613523557312254

In [64]:
data['crim'].std()

8.601545105332487

In [65]:
data['crim'].sum()

1828.4429200000004

In [66]:
data['lstat'].max()

37.97

In [67]:
data['age'].min()

2.9

In [68]:
data['zn'].var()

543.9368136813633

In [69]:
data['age'].median()

77.15

### groupby

In [70]:
# group by chas for crim mean
data.groupby('chas')['crim'].mean()

chas
0    3.744447
1    1.851670
Name: crim, dtype: float64

In [74]:
data.groupby('chas')['age'].mean()

chas
0    67.908626
1    77.500000
Name: age, dtype: float64

### aggregate function

### Advanced Aggregation Functions: Filter()

### Advanced Aggregation Functions: Apply()

## Pivot

### pivot_table()

## Concatenate